mccs_daemon_basename = "mccs-deamon"
mccs_daemon_prefix = "/tmp/mccs"
addrs = ["0.0.0.0", "0.0.0.1", "0.0.0.2", "192.168.211.66", "192.168.211.130", "192.168.211.162", "192.168.211.195"]
listen_port = 5000

[control]
prefix = "/tmp/mccs"
path = "control.sock"

[comm_default_config]
buffer_sizes = [4194304]
channel_count = 3

[comm_global_config]
[comm_global_config.net_rdma]
gid_index = 3
qps_per_conn = 1
timeout = 18
retry_count = 7
pkey = 0
use_inline = false
service_level = 0
traffic_class = 0
adaptive_routing = false
ar_threshold = 8192
pci_relaxed_ordering = false
gdr_flush_disable = true
socket_if_prefix = "rdma"

[comm_global_config.net]
gdr_enable = false
gdr_copy_sync_enable = false
gdr_copy_flush_enable = false

[comm_global_config.shm]
locality = "Sender"
memcpy_send = false
memcpy_recv = false
