mccs_daemon_basename = "mccs-deamon"
mccs_daemon_prefix = "/tmp/mccs-${USER}"
addrs = [
    "0.0.0.0",
    "192.168.211.2",
    "192.168.211.34",
    "192.168.211.66",
    "192.168.211.130",
    "192.168.211.162",
    "192.168.211.195",
]
listen_port = 5000

[control]
prefix = "/tmp/mccs-${USER}"
path = "control.sock"

[comm_default_config]
buffer_sizes = [4194304]
channel_count = 2

[comm_global_config]
[comm_global_config.net_rdma]
gid_index = 3
qps_per_conn = 1
timeout = 18
retry_count = 7
pkey = 0
use_inline = false
service_level = 0
traffic_class = 0
adaptive_routing = false
ar_threshold = 8192
pci_relaxed_ordering = false
gdr_flush_disable = true
socket_if_prefix = "rdma"

[comm_global_config.net]
gdr_enable = false
gdr_copy_sync_enable = false
gdr_copy_flush_enable = false

[comm_global_config.shm]
locality = "Sender"
memcpy_send = false
memcpy_recv = false

[qos_schedule]
epoch_microsecs = 22260000

[qos_schedule.schedule.201]
intervals = [[0, 110000], [420000, 530000], [840000, 950000], [1260000, 1370000], [1680000, 1790000], [2100000, 2210000], [2520000, 2630000], [2940000, 3050000], [3360000, 3470000], [3780000, 3890000], [4200000, 4310000], [4620000, 4730000], [5040000, 5150000], [5460000, 5570000], [5880000, 5990000], [6300000, 6410000], [6720000, 6830000], [7140000, 7250000], [7560000, 7670000], [7980000, 8090000], [8400000, 8510000], [8820000, 8930000], [9240000, 9350000], [9660000, 9770000], [10080000, 10190000], [10500000, 10610000], [10920000, 11030000], [11340000, 11450000], [11760000, 11870000], [12180000, 12290000], [12600000, 12710000], [13020000, 13130000], [13440000, 13550000], [13860000, 13970000], [14280000, 14390000], [14700000, 14810000], [15120000, 15230000], [15540000, 15650000], [15960000, 16070000], [16380000, 16490000], [16800000, 16910000], [17220000, 17330000], [17640000, 17750000], [18060000, 18170000], [18480000, 18590000], [18900000, 19010000], [19320000, 19430000], [19740000, 19850000], [20160000, 20270000], [20580000, 20690000], [21000000, 21110000], [21420000, 21530000], [21840000, 21950000]]
mode = "Allow"

[qos_schedule.schedule.202]
intervals = [[0, 110000], [420000, 530000], [840000, 950000], [1260000, 1370000], [1680000, 1790000], [2100000, 2210000], [2520000, 2630000], [2940000, 3050000], [3360000, 3470000], [3780000, 3890000], [4200000, 4310000], [4620000, 4730000], [5040000, 5150000], [5460000, 5570000], [5880000, 5990000], [6300000, 6410000], [6720000, 6830000], [7140000, 7250000], [7560000, 7670000], [7980000, 8090000], [8400000, 8510000], [8820000, 8930000], [9240000, 9350000], [9660000, 9770000], [10080000, 10190000], [10500000, 10610000], [10920000, 11030000], [11340000, 11450000], [11760000, 11870000], [12180000, 12290000], [12600000, 12710000], [13020000, 13130000], [13440000, 13550000], [13860000, 13970000], [14280000, 14390000], [14700000, 14810000], [15120000, 15230000], [15540000, 15650000], [15960000, 16070000], [16380000, 16490000], [16800000, 16910000], [17220000, 17330000], [17640000, 17750000], [18060000, 18170000], [18480000, 18590000], [18900000, 19010000], [19320000, 19430000], [19740000, 19850000], [20160000, 20270000], [20580000, 20690000], [21000000, 21110000], [21420000, 21530000], [21840000, 21950000]]
mode = "Deny"

# magic number: 49200 & 49202

[[comm_patterns_override]]
communicator_id = 200
channels = [
    { channel_id = 0, ring = [0, 1, 2, 3], udp_sport = [[1, 2, 49202], [3, 0, 49202]], net_dev = "mlx5_0" },
    { channel_id = 1, ring = [0, 1, 2, 3], udp_sport = [[1, 2, 49202], [3, 0, 49202]], net_dev = "mlx5_0" },
]
ib_traffic_class = 106

[[comm_patterns_override]]
communicator_id = 201
channels = [
    { channel_id = 0, ring = [0, 1], udp_sport = [[0, 1, 49200], [1, 0, 49200]], net_dev = "mlx5_0" },
    { channel_id = 1, ring = [0, 1], udp_sport = [[0, 1, 49200], [1, 0, 49200]], net_dev = "mlx5_0" },
]
ib_traffic_class = 66


[[comm_patterns_override]]
communicator_id = 202
channels = [
    { channel_id = 0, ring = [0, 1], udp_sport = [[0, 1, 49200], [1, 0, 49200]], net_dev = "mlx5_0" },
    { channel_id = 1, ring = [0, 1], udp_sport = [[0, 1, 49200], [1, 0, 49200]], net_dev = "mlx5_0" },
]
ib_traffic_class = 66