[package]
name = "cuda-driver-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cuda-finder = { path = "../cuda-finder" }
bindgen = "0.62"